//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicalLogger
{
    using System;
    using System.Collections.Generic;
    
    public partial class genUsuarios
    {
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string nombre { get; set; }
        public string primerApellido { get; set; }
        public string segundoApellido { get; set; }
        public string numeroINE { get; set; }
        public string telefono { get; set; }
        public string contrasena { get; set; }
        public int idPerfil { get; set; }
        public bool estaActivo { get; set; }
    
        public virtual genPerfilUsuario genPerfilUsuario { get; set; }
    }
}
