//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicalLogger
{
    using System;
    using System.Collections.Generic;
    
    public partial class genVentana
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public genVentana()
        {
            this.genSubsistemas = new HashSet<genSubsistemas>();
            this.genLlamada = new HashSet<genLlamada>();
        }
    
        public int idVentana { get; set; }
        public string descripcion { get; set; }
        public int idControl { get; set; }
        public bool estaActivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genSubsistemas> genSubsistemas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genLlamada> genLlamada { get; set; }
        public virtual regcontroles regcontroles { get; set; }
    }
}
