//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicalLogger
{
    using System;
    using System.Collections.Generic;
    
    public partial class regAcciones
    {
        public int idAccion { get; set; }
        public int codigoAccion { get; set; }
        public Nullable<int> idLlamada { get; set; }
        public Nullable<int> idFuncion { get; set; }
        public byte tipoAccion { get; set; }
        public System.DateTime fechaEjecucion { get; set; }
    
        public virtual genAccionesCat genAccionesCat { get; set; }
        public virtual genFuncion genFuncion { get; set; }
        public virtual genLlamada genLlamada { get; set; }
        public virtual regAcciones regAcciones1 { get; set; }
        public virtual regAcciones regAcciones2 { get; set; }
        public virtual regcontroles regcontroles { get; set; }
    }
}
