//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MagicalLogger
{
    using System;
    using System.Collections.Generic;
    
    public partial class regcontroles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public regcontroles()
        {
            this.genVentana = new HashSet<genVentana>();
        }
    
        public int idControl { get; set; }
        public string descripcion { get; set; }
        public string texto { get; set; }
        public byte tipoInteraccion { get; set; }
        public int idAccion { get; set; }
    
        public virtual genControl genControl { get; set; }
        public virtual regAcciones regAcciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<genVentana> genVentana { get; set; }
    }
}
